insert into public.tips (body) values
('Espresso reçetesini sabit tut: doz, çıktı ve süreyi her vardiya başında test shot ile kalibre et.'),
('Süt sürahisini her kullanım sonrası hızlıca durula; eski süt kalıntısı köpük kalitesini ve tadı bozar.'),
('Latte art için süt sıcaklığını 55-65°C bandında tut; daha sıcak süt tatlılığı düşürür.'),
('Yoğun saatte mise-en-place hayat kurtarır: kapak, peçete, şurup ve bardakları erişim sırasına göre diz.'),
('Filtre kahvede öğütüm ve su sıcaklığını birlikte değerlendir; tek değişkeni izole ederek ayar yap.'),
('Açılışta buz makinesinin üretim kapasitesini kontrol et; bar servisinde buz kesintisi hızla akışı bozar.'),
('POS yoğunluğunu azaltmak için en çok satan ürünleri kısa kodlarla tanımla ve ekibi aynı standarda alıştır.'),
('Vardiya devir tesliminde sadece sözlü değil yazılı not bırak; kritik eksikler görünür olur.'),
('Tatlı vitrininde FIFO uygula: önce giren ürün önce satılmalı, fire oranı düşer.'),
('Kasa başlangıç sayımını iki kişiyle çapraz doğrula; gün sonu farklarını azaltır.'),
('Sipariş anonslarını kısa ve standart ver: ürün, boy, ekstra, masa no sırası hatayı azaltır.'),
('Mutfakta kesim tahtası renk kodu kullanmak çapraz bulaşı riskini ciddi oranda düşürür.'),
('Bar ekipmanında günlük hızlı temizlik + haftalık derin temizlik planını ayrı takip et.'),
('Soğuk zincir ürünlerinde dolap kapak açılış sıklığını azalt; sıcaklık dalgalanmasını önlersin.'),
('Krema sifonunda gaz basıncını üretici önerisine göre tut; fazla basınç doku ve güvenliği etkiler.'),
('Kahve değirmeni bıçakları kirliyse en iyi çekirdek bile düz tat verir; düzenli temizlik şart.'),
('Müşteri şikayetinde ilk cümle savunma değil empati olmalı: “Haklısınız, birlikte çözelim.”'),
('Servis hızını artırmanın ilk adımı istasyon düzenidir; adım sayısını azaltan düzen verimi artırır.'),
('Menüde düşük satan kalemleri dönemsel gözden geçir; stok maliyetini ve fireyi optimize et.'),
('Fırın ürünlerinde pişirme sonrası dinlendirme süresine uy; erken kesim doku kaybına yol açar.'),
('Alerjen bilgisini ekip içinde ezber değil görünür checklist ile yönet; hata riskini düşürür.'),
('Bar kapanışında grup başlıklarını kör filtre ile temizleyip backflush yap; acı tat birikimini önler.'),
('Çay ve bitki demlemelerinde su sıcaklığını ürün bazlı ayarla; tek sıcaklık her ürüne uymaz.'),
('Paket siparişlerde etiket standardı belirle: isim, içerik, alerjen, saat bilgisi net olmalı.'),
('Mutfak bıçaklarını düzenli bileylemek sadece hız değil iş güvenliği de sağlar.'),
('Soğuk içecek şuruplarında pompa kalibrasyonu yap; her basımda aynı gramaj tutarlılık sağlar.'),
('Açılış kontrolünde lavabo, sabunluk ve kağıt stoğunu erken tamamla; servis ortasında aksama yaşamazsın.'),
('Sos kaplarında tarih etiketi kullan; gıda güvenliği ve denetim süreçleri kolaylaşır.'),
('Yoğun saat öncesi yarı mamul hazırlığı yap ama raf ömrünü aşmayacak miktarda üretim planla.'),
('Kahve reçetesinde sorun varsa önce öğütüm sonra doz sonra tamp basıncını değerlendir.'),
('Kapanışta “yarına notlar” bölümünü zorunlu tut; sabah ekibi sorunlara hazırlıklı başlar.'),
('Masa devir hızını artırmak için temizlik setini standartlaştır: bez, dezenfektan, çöp poşeti hazır olsun.'),
('Mutfakta termometre kalibrasyonu aylık kontrol edilmeli; yanlış okuma tüm pişirme standardını bozar.'),
('Vardiya içinde mini molaları planlı ver; plansız mola akışı bozarken planlı mola verimi artırır.'),
('Yeni ekip üyesine ilk gün menü ezberi yerine istasyon akışı öğret; hata oranı daha hızlı düşer.'),
('Depo düzeninde kategori bazlı etiketleme yap; sayım süresi kısalır, kritik stok daha erken fark edilir.'),
('İçecek sunumunda bardak sıcaklığı/soğukluğu ürünle uyumlu olmalı; algılanan kaliteyi doğrudan etkiler.'),
('Mutfak-pass-bar iletişiminde tek bir anons dili kullan; farklı kelimeler aynı hataya yol açabilir.'),
('Temizlik kimyasallarını gıdadan ayrı ve etiketli sakla; denetim ve güvenlik için zorunludur.'),
('Şef/barista lideri gün sonunda 5 dakikalık kısa geri bildirim turu yaparsa ertesi gün performans yükselir.');
